version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    commit-message:
      # Prefix all commit messages with "dependabot"
      prefix: "[dependabot]"